Some README.md cleanups
FabricMC/fabric-meta pull request #13
Opened 2021-06-13 15:00 UTC by miiichael

Fix some typos and add a bunch of capitalisation, punctuation and newline tweaks. 😅

2021-06-13 15:01 UTC, haykam821 requested changes

2021-06-13 15:01 UTC, haykam821 commented on README.md
> +Returns the JSON file that should be used in the standard minecraft launcher.
```suggestion
Returns the JSON file that should be used in the standard Minecraft launcher.
```

2021-06-13 15:03 UTC, liach commented
The sheer number of typos in this documentation is scary.

2021-06-13 15:31 UTC, liach commented on README.md
> +Full database, includes all the data. Warning, large JSON.
```suggestion
Full database, includes all the data. **Warning**: large JSON.
```

2021-06-13 16:18 UTC, frqnny requested changes

2021-06-13 16:18 UTC, frqnny commented on README.md
> +Full database, includes all the data. Warning, large JSON.
**Warning** so its the same as liach’s thing.

2021-06-13 16:20 UTC, modmuss50 commented
I am literally blind to spelling mistakes, I try my best. And very much appreciate the help in fixing my mistakes 👍

2021-06-14 01:56 UTC, miiichael commented
All good. I was originally intending to just correct a single spelling mistake. Nek minnit, all the fine tooth combs come out. 😅

2021-06-14 13:03 UTC, modmuss50 approved these changes

2021-06-14 13:06 UTC, sfPlayer1 approved these changes

2021-06-15 18:03 UTC, frqnny approved these changes

2021-06-15 18:03 UTC, frqnny approved these changes

2021-06-16 00:01 UTC, liach approved these changes

2021-06-23 17:30 UTC, merged